name:                aoc2019
version:             0.0.0.1
#synopsis:
#description:
homepage:            https://github.com/incertia/aoc-2019#readme
license:             BSD3
author:              incertia
maintainer:          incertia@incertia.net
copyright:           2019 incertia

extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - data-has
  - hashable
  - lens
  - mtl
  - parsec
  - polysemy
  - polysemy-plugin
  - split
  - time
  - unordered-containers
  - vector

ghc-options:
  - -O2

executables:
  aoc:
    source-dirs:      src
    main:             Main.hs
